### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by iincity** [Heng30/rssbox-android#2]
os: wsl  Ubuntu 20.04.6 LTS
rust : rustc 1.78.0
jdk: openjdk17
andriod sdk:android-sdk_r24.4.1-linux
ndk:android-ndk-r26d-linux
Cargo.toml
[package.metadata.android.sdk]
min_sdk_version = 23
target_sdk_version = 31

--- stderr
  /bin/sh: 1: aarch64-linux-android-ranlib: not found
  /bin/sh: 1: aarch64-linux-android-ranlib: not found
  /bin/sh: 1: aarch64-linux-android-ranlib: not found
  /bin/sh: 1: aarch64-linux-android-ranlib: not found
  /bin/sh: 1: aarch64-linux-android-ranlib: not found
  /bin/sh: 5: aarch64-linux-android-ranlib: not found
  make: *** [Makefile:2457: install_dev] Error 127
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:

  Error installing OpenSSL:
      Command: cd "/home/yuwei/slint/rssbox-android/target/aarch64-linux-android/debug/build/openssl-sys-2fb47db585c1842f/out/openssl-build/build/src" && "make" "install_dev"
      Exit status: exit status: 2

**Comment by heng30** [comment]
有没有设置Android环境变量。我的环境变量是这样的：
```
ANDROID_HOME=/home/blue/Android/Sdk
ANDROID_SDK_ROOT=/home/blue/Android/Sdk
ANDROID_NDK=/home/blue/Android/Sdk/ndk/26.3.11579264
ANDROID_NDK_HOME=/home/blue/Android/Sdk/ndk/26.3.11579264
````

**Comment by iincity** [comment]
export ANDROID_HOME=/home/yu/tools/android-sdk-linux
export ANDROID_SDK_ROOT=/home/yu/tools/android-sdk-linux
export ANDROID_NDK_ROOT=/home/yu/tools/android-ndk-r26d
export ANDROID_NDK=/home/yu/tools/android-ndk-r26d
export ANDROID_NDK_HOME=/home/yu/tools/android-ndk-r26d
export PATH=$PATH:$ANDROID_HOME/tools/bin:$ANDROID_HOME/build-tools:$ANDROID_HOME/platform-tools/bin
这个是设置得环境变量，该设置得都设置了。

**Comment by heng30** [comment]
ndk目录下应该有一个`llvm-ranlib`工具。看样子是没有找到这个工具。
./ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
如果还不行，先编译以下官方的例子：https://github.com/slint-ui/slint/blob/master/examples/energy-monitor/README.md 看看你的环境是否有问题。

**Comment by iincity** [comment]
官方的例子：https://github.com/slint-ui/slint/blob/master/examples/energy-monitor/README.md
是编译成功，估计应该区别在使用了openssl这里

**Comment by heng30** [comment]
ndk目录下应该有`llvm-ranlib` 工具，你的环境中有这个工具吗？安卓的Sdk和ndk建议使用android studio 来安装。

**Comment by iincity** [comment]
这个工具是有的
![image](https://github.com/Heng30/rssbox-android/assets/5435797/15210b16-ee58-4a3a-9fbe-325cfa12724c)

**Comment by heng30** [comment]
将llvm-ranlib工具目录的路径加入到PATH环境变量中，看样子是找不到这个工具。因为我的这个工具在`/usr/bin/llvm-ranlib`中，可能你的环境变量中没有搜到这个工具。

**Comment by iincity** [comment]
> 将llvm-ranlib工具目录的路径加入到PATH环境变量中，看样子是找不到这个工具。因为我的这个工具在`/usr/bin/llvm-ranlib`中，可能你的环境变量中没有搜到这个工具。

确实是路径问题,PATH环境变量里面设置路径错了
